### ISSUE TITLE
Allow usage of Decoder without parsing metadata twice

### ISSUE THREAD

**Issue by noch3** [paritytech/desub#74]
Because of how `Decoder` is written, I can't construct a `Decoder` without consuming `Metadata`. And once I've done that, I can't get the metadata back out without consuming the `Decoder`. Since virtually all of the methods on `Decoder` are already parameterized by lifetime, perhaps `Decoder` itself should be parameterized on lifetime. Or perhaps all those method should simply be a trait on `Metadata` instead and get rid of `Decoder`.

**Comment by noch3** [comment]
I ran into this while trying to make use of the new `ty` information in `CallData`. Can't look up any types since I don't have `Metadata`.

**Comment by jsdw** [comment]
This is a great point; currently I think there is a bias towards being able to store the thing that does decoding, but there are definitely a couple of API changes that we could make to make life easier, I think, as right now you'd be having to convert Metadata back and forth from a Decoder to do things usefully (which is an ergonomic mess, but should be OK performance wise).

My preference would be to expose plain functions from the `decoder` module of the form:

```
pub fn decode_foo(metadata: &Metadata, other, args) -> Result<Foo, DecodeError>
``` 

So that `Metadata` is not consumed (there's no reason for it to be since it's effectively a read-only representation of things).

Alternately, (a weaker preference) `Decoder` could take a reference to `Metadata` as you suggest, which would be a little cleaner if you want to call a bunch of `decode_x` methods each time you create one, but messier if you only need to write `decode_x` once or twice in the code (writing cost of creating decoder vs explicitly passing metadata arg per call).

Or, (and my weakest preference), the current `Decoder` struct could allow you to pluck a reference to Metadata out of it. This sticks to the current API, but in my mind it makes more sense to keep the `Metadata` nice and separate and just have it be a thing that's used by decoding (or eventually encoding) functions as needed.

@insipx what do you reckon?

**Comment by jsdw** [comment]
Just to follow up; I've been thinking about the storage decoding API as part of work I'm currently doing, and the API I'm settling on works quite nicely I think with the "plain functions approach". The decoder module API might be used a bit like this, all together:

```
// Decode an extrinsic (same as current exposed API on Decoder struct):
let extrinsics = decoder::decode_extrinsics(&meta, &extrinsics_bytes)?;
let extrinsic = decoder::decode_extrinsic(&meta, &extrinsic_bytes)?;
let unwrapped_extrinsic = decoder::decode_unwrapped_extrinsic(&meta, &unwrapped_extrinsic_bytes)?;

// Decode storage (the storage decoder can be stored separate, has no lifetimes
// tying it to metadata, and takes some effort to build, and so is optional and cacheable):
let storage_decoder = decoder::decode_storage(&meta);

// Find the prefix (eg "System"), name (eg "Accounts") and type of some storage entry:
let storage_entry_details = storage_decoder.decode_entry(&meta, &extrinsic_bytes)?;

// Decode some values stored at that location (passed metadata, bytes and &TypeId, returns Value):
decoder::decode_value(&meta, &storage_entry_value1, &storage_entry_details.type)?;
decoder::decode_value(&meta, &storage_entry_value2, &storage_entry_details.type)?;
```

The advantages of this API in my mind are:
- We can easily store `Metadata` and `StorageDecoder` (no lifetimes to complicate that).
- We can access `Metadata` at any time (no consuming of metadata by some Decoder struct when really we just need references to it, but also no Decoder struct with lifetimes that makes it hard to store etc).
- `StorageDecoder` requires work to construct, so don't tie it down with lifetimes; make it easy to store for caching etc, and make it optional so we don't do the work unless we want to decode storage.
- Still discoverable; look in `decoder` module and find the top level functions, ideally with examples etc, that decode whatever you're interested in.
- Metadata has the simple purpose of wrapping the `frame_metadata` and exposing information in a relevant way for decoding (and eventually encoding), while being fairly opaque to most things; the interface people care about will be in `decoding` or `encoding` modules.

What do you guys think? I'm tempted to do this wwork as part of my current storage stuff, since it aligns with the API I want for storage offhand.

**Comment by jsdw** [comment]
Draft PR with a "real life" example of this proposed API (including the storage decoding API): https://github.com/paritytech/desub/pull/75

**Comment by noch3** [comment]
Yes that's a perfectly fine option! The only downside is that IDEs don't give you the nice `.<method>` prediction. But this isn't the kind of use case where that matters terribly much. We could get that back by turning `Decoder` into a trait on `Metadata`. But I don't feel strongly for this approach.

**Comment by insipx** [comment]
@jsdw I think the standalones is the path forward then. If a user would want, they'd be able to compose the decoder together with a lifetime and remove the need for a `&meta` argument, so this approach seems to be the more flexible

**Comment by jsdw** [comment]
@insipx great! That was my thinking; keeping things simple and free of lifetimes means you can compose them into higher level things and store them together quite easily :)

@noch3; that's true, although if you type `decoder::` you should still get IDE support :)

<img width="960" alt="Screenshot 2021-11-10 at 15 35 33" src="https://user-images.githubusercontent.com/3799193/141143255-aac3f334-11eb-47ad-8284-4b4c4afe2f7b.png">

**Comment by noch3** [comment]
Great point.

**Comment by dvdplm** [comment]
No opposition from me. Trying to be the devil's advocate, this is all I can come up with:

- if the number of free-standing functions go up over the years it might get a bit messy? (Then otoh the same would be true with lots of methods on a `Decoder`)
- It's a bit odd that there is a storage decoder struct but not a "normal" decoder, i.e. this part of you example:

```rust
let storage_decoder = decoder::decode_storage(&meta);
let storage_entry_details = storage_decoder.decode_entry(&meta, &storage_entry_key)?;
```

One could argue that we should have `decoder::storage_entry(&meta, &storage_key)` too (fluent API yada yada).

**Comment by jsdw** [comment]
> One could argue that we should have decoder::storage_entry(&meta, &storage_key) too (fluent API yada yada).

That's the API I was aiming for; the `StorageDecoder` struct only came into being as an acknowledgement that some actual work needs doing to generate the lookup tables to decode storage, and so that struct is where the result of the work lives, so that it can be cached and such as needed.

(An alternate would have been to always do the work to generate lookup tables on creating metadata, but I'd rather that people could avoid the CPU cycles if they don't care about storage)

**Comment by jsdw** [comment]
I'll close this now as #75 solves the issue :)
